version: "3"
services:
  frontend:
    image: frontend
    build: ./frontend/
    stdin_open: true
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      -  mern-app
    volumes:
    - ./frontend/:/frontend
    - /frontend/node_modules
  api:
    image: api
    build: ./backend/
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks:
      - mern-app
    volumes:
      - ./backend/:/backend
      - /backend/node_modules
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local


